FROM ffreis/base-runner

ARG APP_NAME=__APP_NAME__
ENV APP_NAME=${APP_NAME}

USER root

WORKDIR /run

COPY --chown=appuser:appgroup build/${APP_NAME} ${APP_NAME}

RUN chmod 0750 /run/${APP_NAME}

USER appuser:appgroup

ENTRYPOINT ["/run/entrypoint.sh"]
