FROM ffreis/base

RUN getent group appgroup >/dev/null || groupadd -g 10001 appgroup \
    && id -u appuser >/dev/null 2>&1 || useradd -u 10001 -g appgroup -m -s /usr/sbin/nologin appuser

WORKDIR /run

COPY scripts/entrypoint.sh entrypoint.sh

RUN chmod +x /run/entrypoint.sh

RUN chown -R appuser:appgroup /run

USER appuser:appgroup
